import { IClaim } from "@/app/interfaces/claim.interface";
import { IUser } from "@/app/interfaces/user.interface";

export const mockClaims: IClaim[] = [
  {
    _id: "1",
    insuranceProvider: "Insurance Provider",
    claimType: "Physiotherapy",
    claimDetails: "Session with Dr. Smith",
    date: "2024-05-01",
    status: "PENDING",
    user: "Sangharsha",
  },
  {
    _id: "2",
    insuranceProvider: "Insurance Provider",
    claimType: "Physiotherapy",
    claimDetails: "Session with Dr. Johnson",
    date: "2024-05-08",
    status: "APPROVED",
    user: "Kamala",
  },
  {
    _id: "3",
    insuranceProvider: "Insurance Provider",
    claimType: "Physiotherapy",
    claimDetails: "Session with Dr. Williams",
    date: "2024-05-12",
    status: "PENDING",
    user: "Bipin",
  },
  {
    _id: "4",
    insuranceProvider: "Insurance Provider",
    claimType: "Acupuncture",
    claimDetails: "Session with Dr. Davis",
    date: "2024-05-014",
    status: "REQUIRES ACTION",
    user: "Sudeep",
  },
];

export const mockUsers: IUser[] = [
  {
    _id: "1",
    name: "John Doe",
    email: "john@example.com",
    phone: "123-456-7890",
    address: "123 Main St, Anytown, USA",
    role: "USER",
  },
  {
    _id: "2",
    name: "Jane Smith",
    email: "jane@example.com",
    phone: "234-567-8901",
    address: "456 Oak St, Anytown, USA",
    role: "USER",
  },
  {
    _id: "3",
    name: "Bob Johnson",
    email: "bob@example.com",
    phone: "345-678-9012",
    address: "789 Pine St, Anytown, USA",
    role: "USER",
  },
  {
    _id: "4",
    name: "Alice Williams",
    email: "alice@example.com",
    phone: "456-789-0123",
    address: "123 Cherry St, Anytown, USA",
    role: "THERAPY",
  },
  {
    _id: "5",
    name: "Charlie Brown",
    email: "charlie@example.com",
    phone: "567-890-1234",
    address: "456 Maple St, Anytown, USA",
    role: "THERAPY",
  },
  {
    _id: "6",
    name: "David Davis",
    email: "david@example.com",
    phone: "678-901-2345",
    address: "789 Elm St, Anytown, USA",
    role: "THERAPY",
  },
  {
    _id: "7",
    name: "Eve Evans",
    email: "eve@example.com",
    phone: "789-012-3456",
    address: "123 Pine St, Anytown, USA",
    role: "INSURANCE",
  },
  {
    _id: "8",
    name: "Frank Foster",
    email: "frank@example.com",
    phone: "890-123-4567",
    address: "456 Birch St, Anytown, USA",
    role: "INSURANCE",
  },
  {
    _id: "9",
    name: "Grace Green",
    email: "grace@example.com",
    phone: "901-234-5678",
    address: "789 Cedar St, Anytown, USA",
    role: "INSURANCE",
  },
];
